baseURL = 'https://notes1.projects.pgersl.xyz/'
languageCode = 'en-us'
title = 'Petr Geršl - Notes'
uglyURLs = 'false'
enableEmoji = 'true'
[markup]
    [markup.goldmark.renderer]
        unsafe = 'true'
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 1
[params]
    description = "The official website of Petr Geršl dedicated to his notes and research"
[outputs]
    home = ['HTML', 'JSON', 'RSS']
    page = ['HTML']
[frontmatter]
    date = ['date', 'publishDate', 'lastmod']
    expiryDate = ['expiryDate']
    lastmod = [':git', 'lastmod', 'date', 'publishDate']
    publishDate = ['publishDate', 'date']